# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE are ignored when building from the
# command line, check the gradle/wrapper/gradle-wrapper.properties file.

# When configured, Gradle will run in offline mode and disables network operations.
# org.gradle.offline=true

# Android operating system, and not a virtual machine
# This option should only be used with continious integration servers as it is very demanding on resources
# org.gradle.workers.max=1

# The Kotlin code style for this project: "official" or "obsolete":
# kotlin.code.style=official

android.useAndroidX=true
android.enableJetifier=true
